os: linux
dist: xenial

language: c
node_js:
  - 

addons:
  apt:
    packages:
      - gcc-mingw-w64
      - libc6:i386 # for gluac
      - libstdc++6:i386
      - linux-libc-dev:i386
      - gcc-4.8-multilib
      - libc6-dev-i386
      - luajit
      
before_install:
  # Download the lua checker
  - |
    curl -L 'https://github.com/Metastruct/gtravis/releases/download/travisbins/gluac.tar.xz' |tar -xJf - \
      && export LD_LIBRARY_PATH=`pwd`/gluac${LD_LIBRARY_PATH:+:}${LD_LIBRARY_PATH:-} \
      && export PATH=$PATH:`pwd`/gluac
  
  # Compile luajit for windows libraries
  - |
    curl -L 'https://luajit.org/download/LuaJIT-2.1.0-beta3.tar.gz' |tar -xzf - \
      && pushd LuaJIT-2.1.0-beta3/src/ \
      && make HOST_CC="gcc" CROSS=x86_64-w64-mingw32- TARGET_SYS=Windows BUILDMODE=static \
      && popd
  - nvm install --lts
  - npm install
  
script:
  - ls *.lua | xargs -- gluac -p --
  - CC=x86_64-w64-mingw32-gcc NM=x86_64-w64-mingw32-nm make luastaticlib=./LuaJIT-2.1.0-beta3/src/libluajit.a luaincludedir=./LuaJIT-2.1.0-beta3/src/
  - file *

deploy:
  provider: releases
  token:
    secure: Vz+HkeiCzBk9pI6qQI4wxgYlGkXFhGMAeIpZIROcgLNbIKO2+xGtcepJ1EFclmlPz7sUwrrp0bAD/oxsacZQK7uc5oRreO2XjdwHNS54AFynAAC4vOsWI88+u35yHjF/etCHx+QrRPCjwA42Bzfo4ZQPfpXojiV+Vf4Uxz9zL4Y8Jgr/5oVcU/pK4uazETv65ibC5wSTbS+BKNmHEuURbpM9uasiOYnonKxVn812bLrRMSkV7mP4vM8AQOanT9/bYfC9QPVbaaBHRDiqFpFP1syFuEJ90KgHmBmre8kyzs/HAfGlqIi6QMpDtpsOiPR0ARMWiCasjEHb70cdVQ8TDawHVlZIqdXjFsA/ycXRY6AqoUMVYH5haG5MMcs+hL1gCd+biANXLpdqg+2qcXLcui2rZJhahT2o1LCGPdVsfR3+1xDA1tdl5oUxpk+SNemJCiXvqYYwqvGES9hZZ1rLdsniN4vYQZYDnQeoLyFVfTW/M6hIlrsXzIyDQMSL2bExy92eUsuq3bx5a407m0Xp5jGzY95bORaseN7DB011HJRuKxdX1H56esyrGSPY9/OGLHq1I41KfaLOiaQ3oQVJSUFL66HrtqRrmCGtr93GG6mgrRmW+3pa3Jc08U4uCEffaQyRkH96NWCpjbI88nEcZ4bZSDtF22/kcjxu05kU034=
  file: reslister.exe
  skip_cleanup: true
  on:
    branch: master
branches:
  only:
  - master
